apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: dev
spec:
    selector:
        app: product-app
    type: NodePort
    ports:
        - port: 80
          targetPort: 8080
          nodePort: 30080 # Optional, specify if you want a fixed NodePort