apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-boot-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: spring-boot
    template:
        metadata:
            labels:
                app: spring-boot
        spec:
            containers:
                - name: spring-boot-container
                  image: ram1uj/spring-boot:latest
                  ports:
                      - containerPort: 5000
                  env:
                    - name: APP_MESSAGE
                      valueFrom:
                        secretKeyRef:
                          name: spring-boot-secret
                          key: message