## Datasource Properties for h2 Database

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    ## mysql

    ## url: jdbc:mysql://mysql-0.mysql-h.default.svc.cluster.local:3306/mydb


    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true