apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-job
spec:
  schedule: "0 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            dedicated: cart-app
          containers:
              - name: app-container
                image: busybox
                command: [ "sh","-c", "echo 'Hello, the job is done'" ]




