apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
    selector:
        app: mysql
    type: NodePort
    clusterIP: None
    ports:
        - port: 3306
          targetPort: 3306
          nodePort: 30006