apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql
spec:
    replicas: 3
    selector:
        matchLabels:
          app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql-container
                  image: mysql:latest
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      value: password
                    - name: MYSQL_DATABASE
                      value: mydb
                  ports:
                    - containerPort: 3306

                  volumeMounts:
                        - name: mysql-storage
                          mountPath: /var/lib/mysql


    volumeClaimTemplates:
      - metadata:
          name: mysql-storage
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi

    serviceName: mysql-h

